config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:destroy]
  resources :sessions, only: [:create, :new, :destroy]

  resources :farm_details, except: [:show, :edit, :update, :destroy] do
      get 'edit_selected' , on: :collection
      put 'update_selected', on: :collection
  end

  resources :soils, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :crops, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :reports do
    get 'farm', on: :collection
    get 'crop', on: :collection
    get 'soil', on: :collection
  end

  resources :fertilizers, except: [:show, :edit, :update, :destroy] do
    get 'view', on: :collection
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :posts do
    resources :comments
  end

  root to: "pages#home"
  
  match '/contact',       to: 'pages#contact',    :via => [:get]
  match '/about',         to: 'pages#about',      :via => [:get]
  match '/help',          to: 'pages#help',       :via => [:get]
  match '/signup',        to: 'users#new',        :via => [:get]
  match '/signin',        to: 'sessions#new',     :via => [:get]
  match '/signout',       to: 'sessions#destroy', :via => [:get]
  match '/knowfert',      to: 'farmcropdata#fert_home', :via => [:get]
  match '/knowsoilcrop',      to: 'farmcropdata#soilcrop_home', :via => [:get]

end

app/models/soil.rb
# == Schema Information
#
# Table name: soils
#
#  id                 :integer          not null, primary key
#  farm_detail_id     :integer
#  soil_type          :string(255)
#  soil_texture       :string(255)
#  water_availability :string(255)
#  soil_ph            :string(255)
#  soil_biota         :string(255)
#  season             :string(255)
#  year_of_details    :integer
#  created_at         :datetime
#  updated_at         :datetime
#

class Soil < ActiveRecord::Base


	attr_accessible :soil_type, :soil_texture, :soil_biota, :soil_ph,
						 :water_availability, :season, :year_of_details

	
	validates :soil_type, presence: true
	validates :soil_texture, presence: true
	validates :water_availability, presence: true
	validates :season, presence: true
	validates :year_of_details, presence: true

	belongs_to :farm_detail

	default_scope  { order(created_at: :desc) }

	# def self.fetch_soils(user,from_date,to_date)
	# 	@soils = user.soils.where("soils.created_at between ? and ?", from_date,to_date)
	# 	(@soils.blank?) ? nil : @soils
	# end

	def self.create_csv_file(user,from_date,to_date)
		@soils = user.soils.where("soils.created_at between ? and ?", from_date,to_date)
		if !@soils.blank?
    		file_path = "#{Rails.root}/tmp/soil_report_#{user.id}.csv"
    		CSV.open(file_path, "w+") do |csv|
		    	csv << ["Farm Name", "Soil Type","Soil Texture", "Water Availability", "Soil pH", "Soil is Rich in", "Season", "Year of Details"]
		    	@soils.each do |soil|
		    		farm = soil.farm_detail
		      	csv << [farm.farm_name, farm.soil_type, soil.soil_texture, soil.water_availability, soil.soil_ph, soil.soil_biota, soil.season,soil.year_of_details] 
		      end  
		   end
      end 
      (file_path) ? file_path : nil 
	end

end

app/controllers/soils_controller.rb
class SoilsController < ApplicationController
before_filter :authenticate
before_filter :user_farm_mapping
before_filter :correct_farm_soil_map, only: [:edit_selected]
before_filter :validate_farm, only: [:new]
before_filter :initialize_constants, except: [:index]
   def index
  	   @title = "Soil Details"
      if !params[:search].blank?
         @farm= FarmDetail.search(params[:search])
         logger.debug params
         if !@farm.nil?
            hold_selected_farm(@farm)
            @soil_list = @farm.soils
         else
            @soil_list = nil
         end
      else
         flash.now[:notice] = "Please select a farm!"
      end
   end

   def new
  	   @title = "New Soil Details"
      @newsoil = Soil.new    
   end

   def create    
      @newsoil = selected_farm.soils.build(params[:soil])
    
  	   if @newsoil.save
  		   redirect_to soils_path(search: selected_farm.id), flash: {success: "Added new soil details!"}
  	   else
  		   render 'new'
  	   end
   end

   def edit_selected
      @title = "Edit Soil"
      if params[:soil_id].nil?
         redirect_to soils_path(search: selected_farm.id), flash: {notice: "Please select a Soil to update!"}
      else
         @soil = Soil.find(params[:soil_id])
         if params[:commit] == "Delete"
            @soil.destroy()
            redirect_to soils_path(search: selected_farm.id), flash: {success: "Deleted Soil!"} 
         end            
      end
   end
     
   def update_selected
      @soil = Soil.find(params[:soil_id])
      if @soil.update_attributes(params[:soil])
         redirect_to soils_path(search: selected_farm.id), flash: {success: "Soil details updated!"}
      else
         render 'edit_selected'
      end
   end

   private
    
      def correct_farm_soil_map
         if !params[:soil_id].blank?
            @soil = Soil.find(params[:soil_id])
            @farm = @soil.farm_detail            
            redirect_to home_soils_path unless selected_farm?(@farm) 
         end
      end

      def validate_farm
         @user = selected_farm.user if !selected_farm.nil?
         redirect_to soils_path unless current_user?(@user)      
      end

      def user_farm_mapping
         if params[:search].present?
            @farm= FarmDetail.search(params[:search])
            @user = @farm.user
            redirect_to soils_path(search: nil) unless current_user?(@user)
         end
      end
end

app/helpers/soils_helper.rb
module SoilsHelper
end

app/views/soils/_editSoilFields.html.erb
<%= render "shared/error_messages", object: f.object %>
<table class="tableDetails">
	<tr>
		<td class="field">
			<div><%= f.label :soil_type, "Type of Soil" %></div>
			<div><%=f.select :soil_type, options_for_select(@soil_type_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_type) %></div>
		</td>
		<td class="field">
			<div><%= f.label :soil_texture, "Texture of Soil" %></div>
			<div><%= f.select :soil_texture, options_for_select(@soil_texture_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_texture) %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :season, "Which season?" %></div>
			<div><%= f.select :season, options_for_select(@season_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.season) %></div>
		</td>
		<td class="field">
			<div><%= f.label :year_of_details, "Which year?" %></div>
			<div><%= f.select :year_of_details, options_for_select(2010..2099, selected: f.object.year_of_details) %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :water_availability, "Water Availability" %></div>
			<div><%= f.select :water_availability,  options_for_select(@quantity_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.water_availability) %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :soil_ph, "Soil pH level" %></div>
			<div><%= f.select :soil_ph, options_for_select(@soil_ph_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_ph) %></div>
		</td>
		<td class="field">
			<div><%= f.label :soil_biota, "Contains high amount of" %></div>
			<div><%= f.select :soil_biota, options_for_select(@soil_biota_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_biota) %></div>
		</td>
	</tr>
	
</table>

app/views/soils/_newSoilFields.html.erb
<%= render "shared/error_messages", object: f.object %>
<table class="tableDetails">
	<tr>
		<td class="field">
			<div><%= f.label :soil_type, "Type of Soil" %></div>
			<div><%=f.select :soil_type, options_for_select(@soil_type_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_type), prompt: '--Select--' %></div>
		</td>
		<td class="field">
			<div><%= f.label :soil_texture, "Texture of Soil" %></div>
			<div><%= f.select :soil_texture, options_for_select(@soil_texture_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_texture), prompt: '--Select--' %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :season, "Which season?" %></div>
			<div><%= f.select :season, options_for_select(@season_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.season), prompt: '--Select--' %></div>
		</td>
		<td class="field">
			<div><%= f.label :year_of_details, "Which year?" %></div>
			<div><%= f.select :year_of_details, options_for_select(2010..2099, selected: f.object.year_of_details) %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :water_availability, "Water Availability" %></div>
			<div><%= f.select :water_availability,  options_for_select(@quantity_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.water_availability), prompt: '--Select--' %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :soil_ph, "Soil pH level" %></div>
			<div><%= f.select :soil_ph, options_for_select(@soil_ph_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_ph), prompt: '--Select--' %></div>
		</td>
		<td class="field">
			<div><%= f.label :soil_biota, "Contains high amount of" %></div>
			<div><%= f.select :soil_biota, options_for_select(@soil_biota_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.soil_biota), prompt: '--Select--' %></div>
		</td>
	</tr>
</table>

app/views/soils/edit_selected.html.erb
<div id="editSoil">
<h2 class="sideHeading">Update Soil Details</h2>
<%= form_for(@soil, :url => update_selected_soils_path, :html => { :method => :put }) do |fields| %>
<%= hidden_field_tag :soil_id, @soil.id %>
<%= render "editSoilFields", f:fields %>
<div class="button_align">
		<ul>
			<li><%= fields.submit "Submit", class: 'submit_button' %></li>
			<li><%= link_to "Cancel", soils_path(search: selected_farm.id), class: 'submit_button' %></li>
		</ul>
	</div>
<% end%>
</div>

app/views/soils/index.html.erb
<div id="soilDetailsHome">
	<h2 class="sideHeading">Soil Details</h2>
	<%= form_tag soils_path, method: 'get' do %>
		<% @farm= current_user.farm_details %>
		<div class="searchField">
			<%= select_tag :search, options_for_select(@farm.collect{ |u| [u.farm_name, u.id] },selected: params[:search]), prompt: 'Please select' %>
			<%= submit_tag "Search", name: nil ,class: 'submit_button' %>
		</div>
	<% end %>

	<% if !params[:search].blank?  %>
	&nbsp&nbsp&nbsp&nbsp<%= link_to "<button>Add Soil Details</button>".html_safe, new_soil_path %>
	</br></br>

	<% if !@soil_list.blank? %>
	<div class="tableIndex">
	<%= form_tag(edit_selected_soils_path, method:'get') do %>
		<table>
			<thead>
				<tr>
					<th></th>
					<th>Type of Soil</th>
					<th>Soil Texture</th>
					<th>Water Availability</th>
					<th>Soil ph</th>
					<th>Soil Biota</th>
					<th>Season</th>
					<th>Year of Details</th>
				</tr>
			</thead>
			<% for soil in @soil_list %>
				<tbody>
					<tr>
						<td><%= radio_button_tag :soil_id, soil.id %></td>
						<td><%= soil.soil_type %></td>
						<td><%= soil.soil_texture %></td>
						<td><%= soil.water_availability %></td>
						<td><%= soil.soil_ph %></td>
						<td><%= soil.soil_biota %></td>
						<td><%= soil.season %></td>
						<td><%= soil.year_of_details %></td>
					</tr>
				</tbody>
			<% end %>
		</table>
		<div class="editDel_buttons">
			<ul>
				<li><%= submit_tag "Edit", name: nil %></li>
				<li><%= submit_tag "Delete", data: { confirm: "Are you sure?", title: "Delete Soil" } %></li>
			</ul>
		</div>
	<% end %>
	</div>
	<% end %>
	<% end %>
</div>

app/views/soils/new.html.erb
<div id="addSoilDetails">
	<h2 class="sideHeading">Add Soil Details</h2>
	<%= form_for(@newsoil) do |fields|%>
		<%= render "newSoilFields", f:fields%>
		<div class="button_align">
			<ul>
				<li><%= fields.submit "Submit", class: 'submit_button' %></li>
				<li><%= link_to "Cancel", soils_path(search: selected_farm.id), class: 'submit_button' %></li>
			</ul>
		</div>	
	<% end%>
</div>