config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:destroy]
  resources :sessions, only: [:create, :new, :destroy]

  resources :farm_details, except: [:show, :edit, :update, :destroy] do
      get 'edit_selected' , on: :collection
      put 'update_selected', on: :collection
  end

  resources :soils, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :crops, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :reports do
    get 'farm', on: :collection
    get 'crop', on: :collection
    get 'soil', on: :collection
  end

  resources :fertilizers, except: [:show, :edit, :update, :destroy] do
    get 'view', on: :collection
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :posts do
    resources :comments
  end

  root to: "pages#home"
  
  match '/contact',       to: 'pages#contact',    :via => [:get]
  match '/about',         to: 'pages#about',      :via => [:get]
  match '/help',          to: 'pages#help',       :via => [:get]
  match '/signup',        to: 'users#new',        :via => [:get]
  match '/signin',        to: 'sessions#new',     :via => [:get]
  match '/signout',       to: 'sessions#destroy', :via => [:get]
  match '/knowfert',      to: 'farmcropdata#fert_home', :via => [:get]
  match '/knowsoilcrop',      to: 'farmcropdata#soilcrop_home', :via => [:get]

end

app/models/crop.rb
# == Schema Information
#
# Table name: crops
#
#  id             :integer          not null, primary key
#  crop_name      :string(255)
#  crop_acarage   :integer
#  season         :string(255)
#  from_date      :date
#  to_date        :date
#  expected_yeild :integer
#  actual_yeild   :integer
#  Other_details  :text
#  created_at     :datetime
#  updated_at     :datetime
#  farm_detail_id :integer
#

class Crop < ActiveRecord::Base
	

	attr_accessible :crop_name, :crop_acarage, :season, :from_date, :to_date,
						:expected_yeild, :actual_yeild, :Other_details

	validates	:crop_name, presence: true
	validates	:crop_acarage,presence: true,
					 numericality: { only_integer: true, greater_than: 0 }
	validate		:crop_acarage_greater_than_farm_area, on: [:create]
	validate    :crop_acarage_greater_than_farm_area_update, on: [:update]
	validates	:season, presence: true
	validates	:from_date, presence: true
	validates	:to_date, presence: true
	validate 	:to_date_greater_than_from_date, on:[:create, :update]
	validates	:expected_yeild, presence: true

	belongs_to :farm_detail
	has_many	  :fertilizers, dependent: :destroy
	has_one	  :user, through: :farm_detail

	default_scope  { order(created_at: :desc) }
	
	def self.search(crop_id)
		crop = Crop.find_by_id(crop_id)
		(crop) ? crop : nil
	end

	def self.find_by_farm_and_year(farm, year)
		if Rails.env.development?
			@crops = farm.crops.where("strftime('%Y', crops.created_at) = '?'", year)
		else
			@crops = farm.crops.where("extract(year from crops.created_at) = '?'", year)
		end
		(@crops.any?) ? @crops : [nil]
	end

	def self.create_csv_file(user,from_date,to_date)
		@crops = user.crops.where("crops.created_at between ? and ?", from_date,to_date)
		if !@crops.blank?
    		file_path = "#{Rails.root}/tmp/crop_report_#{user.id}.csv"
    		CSV.open(file_path, "w+") do |csv|
	    		csv << ["Farm Name", "Farm Area", "Soil Type","Crop Name", "Acarage", "Season", "Farm Start Date", "Farm End Date", "Expected Yeild", "Actual Yeild", "Other Details"]
	    		@crops.each do |crop|
	    			farm = crop.farm_detail
	      		csv << [farm.farm_name, farm.farm_area, farm.soil_type, crop.crop_name, crop.crop_acarage, crop.season, crop.from_date, crop.to_date, crop.expected_yeild, crop.actual_yeild, crop.Other_details] 
	      	end
	      end  
      end
      (file_path) ? file_path : nil 
	end

	def available_crop_area(farm)
		@crops = farm.crops.where("to_date >= ?", Date.today)
		if @crops.blank?
			available_crop_area = farm.farm_area
		else
			crop_area = 0
			for crop in @crops
				crop_area += crop.crop_acarage
			end
			farm_area = farm.farm_area
			if crop_area == 0
				available_crop_area = farm_area
			else
				available_crop_area = farm_area - crop_area
			end
		end	
	end

private
	def crop_acarage_greater_than_farm_area
		if crop_acarage.present? && crop_acarage > available_crop_area(self.farm_detail)
     		errors.add(:crop_acarage, "greater than available farm area")
    	end
  	end

  	def crop_acarage_greater_than_farm_area_update
    	if crop_acarage >	(available_crop_area(self.farm_detail) + self.crop_acarage_was)
     		errors.add(:crop_acarage, "greater than available farm area")
    	end
  	end

  	def to_date_greater_than_from_date
  		if to_date.present? && to_date <= from_date
  			errors.add(:to_date, "should be grater than From date")
  		end
  	end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
before_filter :authenticate
before_filter :user_farm_mapping
before_filter :correct_farm_crop_map, only: [:edit_selected]
before_filter :initialize_constants, except: [:index]

	def index
	  	@title = "Crop Details"
	  	if !params[:search].blank?
		  	@farm= FarmDetail.search(params[:search])
		 	if !@farm.nil?
		  		hold_selected_farm(@farm)
		  		@crops=@farm.crops
			else
				@crops = nil
			end
		else
         flash.now[:notice] = "Please select a farm!"
      end
	end

	def new
		@title = "New Crop"
		@crop = Crop.new		
	end

	def create
		@crop = selected_farm.crops.build(params[:crop])
	  	if @crop.save
	  		redirect_to crops_path(search: selected_farm.id), flash: {success: "Added new crop!"}
	  	else
	  		render 'new'
	  	end
	end

   def edit_selected
      @title = "Edit Crop"
      if params[:crop_id].nil?
         redirect_to crops_path(search: selected_farm.id), flash: {notice: "Please select a Crop to update!"}
      else
         @crop = Crop.find(params[:crop_id])
         if params[:commit] == "Delete"
            @crop.destroy()
            redirect_to crops_path(search: selected_farm.id), flash: {success: "Deleted crop!"} 
         end            
      end
   end
     
   def update_selected
      @crop = Crop.find(params[:crop_id])
      if @crop.update_attributes(params[:crop])
         redirect_to crops_path(search: selected_farm.id), flash: {success: "Crop details updated!"}
      else
         render 'edit_selected'
      end
   end


	private
		def user_farm_mapping
			if params[:search].present?
				@farm= FarmDetail.search(params[:search])
				@user = @farm.user
				redirect_to crops_path(search: nil) unless current_user?(@user)
			end
		end
	   
	  	def correct_farm_crop_map
	  		if !params[:crop_id].blank?
	    		@crop = Crop.find(params[:crop_id])
	    		@farm = @crop.farm_detail            
	   		redirect_to crops_path unless selected_farm?(@farm)  
	   	end
	  	end

end

app/helpers/crops_helper.rb
module CropsHelper
end

app/views/crops/_editCropFields.html.erb
<%= render "shared/error_messages", object: f.object %>
<table class="tableDetails">
	<tr>
		<td class="field">
		<div><%= f.label :crop_name, "Crop Name" %></div>
		<div><%=f.select :crop_name, options_for_select(@crop_name_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.crop_name) %></div>
		</td>
		<td class="field">
			<div><%= f.label :crop_acarage, "Crop Acarage" %></div>
			<div><%= f.number_field :crop_acarage, placeholder: "#{(@crop.available_crop_area(selected_farm)+@crop.crop_acarage_was)} acres is available" %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :season, "Season" %></div>
			<div><%= f.select :season, options_for_select(@season_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.season) %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :from_date, "Crop start date" %></div>
			<div><%= f.date_field :from_date %></div>
		</td>
		<td class="field">
			<div><%= f.label :to_date, "Crop end date" %></div>
			<div><%= f.date_field :to_date %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :expected_yeild %></div>
			<div><%= f.number_field :expected_yeild,:placeholder => "Enter value in tons" %></div>
		</td>
		<td class="field">
			<div><%= f.label :actual_yeild %></div>
			<div><%= f.number_field :actual_yeild, :placeholder => "Enter value in tons" %></div>
		</td>
	</tr>
</table>

app/views/crops/_newCropFields.html.erb
<%= render "shared/error_messages", object: f.object %>
<table class="tableDetails">
	<tr>
		<td class="field">
		<div><%= f.label :crop_name, "Crop Name" %></div>
		<div><%=f.select :crop_name, options_for_select(@crop_name_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.crop_name), prompt: '--Select--' %></div>
		</td>
		<td class="field">
			<div><%= f.label :crop_acarage, "Crop Acarage" %></div>
			<div><%= f.number_field :crop_acarage, placeholder: "#{@crop.available_crop_area(selected_farm)} acres is available" %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :season, "Season" %></div>
			<div><%= f.select :season, options_for_select(@season_con.collect{ |u| [u.lookup_value, u.lookup_value] }, selected: f.object.season), prompt: '--Select--' %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :from_date, "Crop start date" %></div>
			<div><%= f.date_field :from_date %></div>
		</td>
		<td class="field">
			<div><%= f.label :to_date, "Crop end date" %></div>
			<div><%= f.date_field :to_date %></div>
		</td>
	</tr>
	<tr>
		<td class="field">
			<div><%= f.label :expected_yeild %></div>
			<div><%= f.number_field :expected_yeild,:placeholder => "Enter value in tons" %></div>
		</td>
		<td class="field">
			<div><%= f.label :actual_yeild %></div>
			<div><%= f.number_field :actual_yeild, :placeholder => "Enter value in tons" %></div>
		</td>
	</tr>
</table>

app/views/crops/edit_selected.html.erb
<div id="editCrop">
	<h2 class="sideHeading">Update Crop Details</h2>
	<%= form_for(@crop, :url => update_selected_crops_path, :html => { :method => :put }) do |fields| %>
		<%= hidden_field_tag :crop_id, @crop.id %>
		<!--<%= fields.hidden_field :id %>-->
		<%= render "editCropFields", f:fields %>
		<div class="button_align">
				<ul>
					<li><%= fields.submit "Submit", class: 'submit_button' %></li>
					<li><%= link_to "Cancel", crops_path(search: selected_farm.id), class: 'submit_button' %></li>
				</ul>
			</div>
	<% end%>
</div>

app/views/crops/index.html.erb
<div id="cropDetailsHome">
	<h2 class="sideHeading">Crop Details</h2>
	<%= form_tag crops_path, method: 'get' do %>
		<% @farm= current_user.farm_details %>
		<div class="searchField">
			<%= select_tag :search, options_for_select(@farm.collect{ |u| [u.farm_name, u.id] },selected: params[:search]), prompt: 'Please select' %>
			<%= submit_tag "Search", name: nil ,class: 'submit_button' %>
		</div>
	<% end %>
	<% if !params[:search].blank?  %>
		&nbsp&nbsp&nbsp&nbsp<%= link_to "<button>Add Crop Details</button>".html_safe, new_crop_path %>
	<br/><br/>
	<% if !@crops.blank? %>
	<div class="tableIndex">
	<%= form_tag(edit_selected_crops_path, method:'get') do %>
		<table>
			<thead>
				<th></th>
				<th>Crop Name</th>
				<th>Acarage</th>
				<th>Season</th>
				<th>From</th>
				<th>To</th>
				<th>Exp yeild(in tons)</th>
				<th>Actual yeild(in tons)</th>
				<th>Other Details</th>
			</thead>
			<tbody>
				<% for crop in @crops %>
					<tr>
					<td><%= radio_button_tag :crop_id, crop.id %></td>
					<td><%= crop.crop_name %></td>
					<td><%= crop.crop_acarage %></td>
					<td><%= crop.season  %></td>
					<td><%= crop.from_date %></td>
					<td><%= crop.to_date  %></td>
					<td><%= crop.expected_yeild  %></td>
					<td><%= crop.actual_yeild  %></td>
					<td><%= crop.Other_details  %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div class="editDel_buttons">
			<ul>
				<li><%= submit_tag "Edit", name: nil %></li>
				<li><%= submit_tag "Delete", data: { confirm: "Are you sure?", title: "Delete Crop" } %></li>
			</ul>
		</div>
	<% end %>
	</div>
	<% end %>
	<% end %>
</div>

app/views/crops/new.html.erb
<div id="addCropDetails">
	<h2 class="sideHeading">Add Crop Details</h2>
	<%= form_for(@crop) do |fields|%>
		<%= render "newCropFields", f:fields%>
		<div class="button_align">
			<ul>
				<li><%= fields.submit "Submit", class: 'submit_button' %></li>
				<li><%= link_to "Cancel", crops_path(search: selected_farm.id), class: 'submit_button' %></li>
			</ul>
		</div>	
	<% end%>
</div>