config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:destroy]
  resources :sessions, only: [:create, :new, :destroy]

  resources :farm_details, except: [:show, :edit, :update, :destroy] do
      get 'edit_selected' , on: :collection
      put 'update_selected', on: :collection
  end

  resources :soils, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :crops, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :reports do
    get 'farm', on: :collection
    get 'crop', on: :collection
    get 'soil', on: :collection
  end

  resources :fertilizers, except: [:show, :edit, :update, :destroy] do
    get 'view', on: :collection
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :posts do
    resources :comments
  end

  root to: "pages#home"
  
  match '/contact',       to: 'pages#contact',    :via => [:get]
  match '/about',         to: 'pages#about',      :via => [:get]
  match '/help',          to: 'pages#help',       :via => [:get]
  match '/signup',        to: 'users#new',        :via => [:get]
  match '/signin',        to: 'sessions#new',     :via => [:get]
  match '/signout',       to: 'sessions#destroy', :via => [:get]
  match '/knowfert',      to: 'farmcropdata#fert_home', :via => [:get]
  match '/knowsoilcrop',      to: 'farmcropdata#soilcrop_home', :via => [:get]

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base

	attr_accessible :content, :user_id
	validates :user_id, presence: true

	belongs_to :user
	has_many :comments, dependent: :destroy

	default_scope  { order(created_at: :desc) }

   def self.uncommented
   	joins(:comments).where 'posts.id not in comments.post_id'
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_filter :authenticate

def index
	if params[:type] == "All Posts"
		@title = 'All Posts'
		@posts = Post.all
	elsif params[:type] == "Unanswered Posts"
		@title = 'Unanswered Posts'
		@posts = Post.where('comments_count = 0')
	else
		@title = 'My Posts'
		@posts = current_user.posts
	end
end

def new
	@title = "New Post"
	@post = Post.new
end

def create
	@post=current_user.posts.build(params[:post])
   if @post.save
      redirect_to posts_path, flash: {success: "Post submitted!"}
   else
 		@title = "New Post"
      render 'new'
   end
end

def show
	@title = "View Question"
	@post = Post.find(params[:id])
	@post_comments = @post.comments
	@comment = Comment.new
end

def destroy
   Post.find(params[:id]).destroy
   redirect_to posts_path, flash: {success: "Post deleted!"}
end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div id="postsHome">
<h2 class="sideHeading">Farmer Questions</h2>
<div id="postQuestion">
&nbsp&nbsp&nbsp&nbsp
<span>Have a Question? Post it here.</span> <%= link_to "<button>Ask Question</button>".html_safe, new_post_path %>
</div>

<div id="postTabs"> 
	<ul>
		<li><%= link_to "My Posts(#{current_user.posts.count})", posts_path(type: "My Posts") %></li>
		<li><%= link_to "Unanswered Posts(#{Post.where('comments_count = 0').count})", posts_path(type: "Unanswered Posts") %></li>
		<li><%= link_to "All Posts(#{Post.count})", posts_path(type: "All Posts") %></li>
	</ul>
</div>
<div id="postContent">
	<table class="tableDetails">
	<tr>
		<% if @posts.present? %>
		<td class="field"><h3>Questions</h3>
		<ol>
		<% @posts.each do |post| %>
			<li style = "border-bottom: 1px solid #dadada">
			<p style="font-size: 120%"><%= link_to post.content, post_path(post) %></p>
				<span style="line-height: 1px;">
				<small>
					<p style="font-size: 95%">--Posted by <%= link_to post.user.first_name, user_path(post.user) %> <%= time_ago_in_words(post.created_at)%> ago</p>
				</small>
			</span>
			</li>
		<% end %>
		</ol>
		</td>
		<% end %>
		</tr>
	</table>
	</div>
</div>

app/views/posts/new.html.erb
<%= form_for(@post) do |f|%>
<%= render "shared/error_messages", object: f.object %>
   <table class="tableDetails">
   	<tr>
   		<td class="field">
   			<label>Your Question</label>
   		</td>
   		</tr>
   	<tr>
   		<td class="field">
   		<%= f.text_area :content, class: "message_area" %>
   		</td>
   	</tr>
   </table>
   <div class="button_align">
		<ul>
			<li><%= f.submit "Submit", class: 'submit_button' %></li>
			<li><%= link_to "Cancel", posts_path, class: 'submit_button' %></li>
		</ul>
	</div>	
<% end%>

app/views/posts/show.html.erb
<div id="showQuestion">
	<h2 class="sideHeading">Question Details</h2>
	<table class="tableDetails">
	<tr>
		<td class="field">
			<h2><%= link_to @post.content, post_path(@post) %></h2>
		</td>
		<!-- <td>
			<%= link_to "<button>Delete</button>".html_safe, @post, method: "delete",
	                                                   confirm: "Are you sure?" %>
		</td> -->
	</tr>
	<tr>
		<td class="field">
		<% if @post_comments.present? %>
		<h3>Answers</h3>
		<div>
		<ol>
		<% @post_comments.each do |comment| %>
			<li style = "border-bottom: 1px solid #dadada">
			<p> <%= comment.content %> </p>
			<span style="line-height: 1px;"> 
			<small>
				<p style="font-size: 95%">--Posted by <%= comment.user.first_name %> <%= time_ago_in_words(comment.created_at) %> ago</p>
			</small>
			</span>
			<% end %>
			</li>
		</ol>
		</div>
		<% else %>
			<p style = "border-bottom: 1px solid #dadada"> &nbsp No Answers </p>
		<% end %>
		<%= render 'comments/comments_form',  post:@post %>
		</td>
	</tr>
   </table>
</div>