config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:destroy]
  resources :sessions, only: [:create, :new, :destroy]

  resources :farm_details, except: [:show, :edit, :update, :destroy] do
      get 'edit_selected' , on: :collection
      put 'update_selected', on: :collection
  end

  resources :soils, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :crops, except: [:show, :edit, :update, :destroy] do
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :reports do
    get 'farm', on: :collection
    get 'crop', on: :collection
    get 'soil', on: :collection
  end

  resources :fertilizers, except: [:show, :edit, :update, :destroy] do
    get 'view', on: :collection
    get 'edit_selected', on: :collection
    put 'update_selected', on: :collection
  end

  resources :posts do
    resources :comments
  end

  root to: "pages#home"
  
  match '/contact',       to: 'pages#contact',    :via => [:get]
  match '/about',         to: 'pages#about',      :via => [:get]
  match '/help',          to: 'pages#help',       :via => [:get]
  match '/signup',        to: 'users#new',        :via => [:get]
  match '/signin',        to: 'sessions#new',     :via => [:get]
  match '/signout',       to: 'sessions#destroy', :via => [:get]
  match '/knowfert',      to: 'farmcropdata#fert_home', :via => [:get]
  match '/knowsoilcrop',      to: 'farmcropdata#soilcrop_home', :via => [:get]

end

app/views/layouts/_footer.html.erb
<div id="footer">
   <nav>
	   <ul>
   		<li><%= link_to "About", about_path%></li>
     	   <li><%= link_to "Contact", contact_path%></li>
     		<li><%= link_to "Help", help_path %></li>
   	</ul>
	</nav>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <!-- <%= link_to logo_image_helper, root_path%> -->
  <h1>Farm Management</h1>
</div>

app/views/layouts/_leftColumnLinks.html.erb
<div id="leftcolumn">
  <% if signed_in?%>
	<ul class="sidebar">
		<li><%= link_to "Farm Details", farm_details_path %></li>
		<li><%= link_to "Soil Details", soils_path%></li>
		<li><%= link_to "Crop Details", "#" %></li>
	</ul>
	<% end%>
</div> 

app/views/layouts/_navigation.html.erb
<div id="navigation">
  <div id='cssmenu'>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Soils", knowsoilcrop_path %></li>
      <li><%= link_to "Fertilizers", knowfert_path %></li>
      <% if signed_in?%>
        <li class='has-sub'><a><span>My Farm</span></a>
            <ul>
              <li><%= link_to "Farm Details", farm_details_path %></li>
              <li><%= link_to "Soil Details", soils_path%></li>
              <li><%= link_to "Crop Details", crops_path %></li>
              <li><%= link_to "Fertilizer Details", fertilizers_path %></li>
              <li class="last"><%= link_to "Reports", reports_path %></li>
            </ul>
        </li>
        <li><%= link_to "Forum", posts_path %></a>
        </li>
      <% end%>
    </ul>
  </div>
  <div id="sub-nav">
    <nav>
      <ul>
        <% if signed_in?%>
    	    <li><%= link_to "Profile", user_path(current_user)%></li>
        <% end %>
        <% if signed_in?%>
          <li class='last'><%= link_to "Sign Out", signout_path %></li>
        <% else%>
          <li class='last'><%= link_to "Sign In", signin_path %></li>
        <% end%>
      </ul>
    </nav>
  </div>
      
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
    <%= yield :page_head %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'blueprint/screen', media: 'screen'%>
	  <%= stylesheet_link_tag 'custom', media: 'screen'%>
    <%= stylesheet_link_tag 'login', media: 'screen'%>
    <%= stylesheet_link_tag 'menu', media: 'screen' %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js","application" %>
    <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
    <%= javascript_include_tag 'application' %>
</head>

<body onunload="">
  <div id="wrapper">

    <%= render 'layouts/header'%>

    <%= render 'layouts/navigation'%>

<!--     <%= render 'layouts/leftColumnLinks'%> -->
        
    <div id="content">
      <% flash.each do |key,value| %>
        <div class="flash <%= key%>"><%= value%></div>
      <%end%>
    <%= yield %>
    </div>
  
    <%= render 'layouts/footer'%>
  </div>
   <div id="debug">
    <%= debug(params) if Rails.env.development?%>
  </div>
</body>
</html>
	